service: auction-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
    MAIL_QUEUE_URL: ${self:custom.MailQueue.url}
  iamRoleStatements:
    - ${file(iam/AuctionsTable.yml):AuctionsTableIAM}
    - ${file(iam/MailQueueIAM.yml):MailQueueIAM}
  apiGateway:
    shouldStartNameWithService: true

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}


functions: ${file(functions/functions.yml):Functions}

custom:
  Auth:
    authorizer: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:dav-serverless-auth0-${self:provider.stage}-auth
  AuctionsTable:
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn
  MailQueue:
    arn: ${cf:dav-serverless-notifications-${self:provider.stage}.MailQueueArn}
    url: ${cf:dav-serverless-notifications-${self:provider.stage}.MailQueueUrl}

# <linking: false> is not recommended for production or if you collaborate with your team
#custom:
#  bundle:
#    linting: false
