service: auction-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  apiGateway:
    shouldStartNameWithService: true

resources:
  Resources:
    AuctionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AuctionsTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttribiteType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

functions:
  hello:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
