service: auction-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  apiGateway:
    shouldStartNameWithService: true

resources:


functions:
  hello:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
